[build]
  command = "npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# ✅ REMOVE all trailing slash redirects - let Nuxt handle everything
# Only keep the SPA fallback

# SPA fallback for unmatched routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
