[build]
  command = "npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# ✅ CRITICAL: Server-level trailing slash redirects (handles before SPA)
# This must come BEFORE the SPA fallback to prevent redirect loops

# Remove trailing slashes from all paths except root
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
  force = true

# Keep specific exceptions for directories that need trailing slashes
[[redirects]]
  from = "/admin/*/"
  to = "/admin/:splat"
  status = 301
  force = true

# SPA fallback for unmatched routes (must be LAST)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
