// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },

  modules: [
    '@nuxtjs/seo', // 🆕 Add this first for comprehensive SEO
    '@nuxt/content', 
    '@nuxtjs/tailwindcss', 
    '@nuxt/image'
    // Removed '@nuxtjs/sitemap' - included in @nuxtjs/seo
  ],

  // 🆕 Add site configuration for @nuxtjs/seo
  site: {
    url: 'https://dobbiniplaw.com',
    name: 'Dobbin IP Law P.C.',
    description: 'Utah patent attorney providing clear, strategic IP protection for inventors and businesses',
    defaultLocale: 'en'
  },

  // 🔧 Fix robots configuration - this was causing indexability issues
  robots: {
    credits: false, // Remove the "Generated by" comment
    sitemap: 'https://dobbiniplaw.com/sitemap.xml',
    rules: [
      {
        UserAgent: '*',
        Allow: '/',
        // Remove problematic Disallow rules
      }
    ]
  },

  // 🔧 Enhanced sitemap configuration with explicit indexability
  sitemap: {
    siteUrl: 'https://dobbiniplaw.com',
    autoLastmod: true,
    exclude: ['/drafts/**', '/admin/**'],
    sources: [
      '/sitemap.xml'
    ],
    defaults: {
      changefreq: 'monthly',
      priority: 0.8
    }
  },
  
  content: {
    documentDriven: true,
    highlight: {
      theme: 'github-light'
    }
  },  

  css: [
    '~/assets/css/main.css',
    '@fortawesome/fontawesome-svg-core/styles.css'
  ],

  // 🔧 Fix trailing slash issues (CRITICAL for canonicals)
  router: {
    options: {
      scrollBehavior: () => false,
      trailingSlash: false
    }
  },

  app: {
    pageTransition: {
      name: 'page',
      mode: 'out-in'
    },
    head: {
      title: 'Dobbin IP Law P.C. | Protecting Your Work',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' },
        { name: 'description', content: 'Dobbin IP Law specializes in obtaining patents to protect your invention, copyrights to protect your authorship, and trademarks to protect your marketing.' },
        // 🔧 Add default robots meta tag for indexability
        { name: 'robots', content: 'index, follow' }
      ],
      link: [
        { rel: 'icon', href: '/favicon-32x32.png', sizes: '32x32' },
        { rel: 'icon', href: '/favicon-192x192.png', sizes: '192x192' },
        { rel: 'apple-touch-icon', href: '/favicon-180x180.png' },
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Crimson+Text:regular,italic,600,600italic,700,700italic&subset=latin&display=swap' }
      ],
      script: [
        {
          innerHTML: `
            if (window.netlifyIdentity) {
              window.netlifyIdentity.on("init", user => {
                if (!user) {
                  window.netlifyIdentity.on("login", () => {
                    document.location.href = "/admin/";
                  });
                }
              });
            }
          `,
          type: 'text/javascript',
          body: true
        },
        {
          innerHTML: `
            window.addEventListener('load', function() {
              window.scrollTo(0, 0);
            });
            
            window.forceScrollToTop = function() {
              window.scrollTo(0, 0);
            }
          `,
          type: 'text/javascript',
          body: true
        }
      ]
    }
  },

  // Image optimization for Core Web Vitals
  image: {
    formats: ['webp', 'avif'],
    screens: {
      xs: 320,
      sm: 640,
      md: 768,
      lg: 1024,
      xl: 1280
    },
    quality: 85,
    densities: [1, 2]
  },

  build: {
    transpile: [
      '@fortawesome/fontawesome-svg-core',
      '@fortawesome/free-solid-svg-icons',
      '@fortawesome/vue-fontawesome'
    ]
  },

  ssr: true,
  
  nitro: {
    preset: 'netlify',
    compressPublicAssets: true,
    prerender: {
      crawlLinks: true,
      routes: [
        '/',
        '/about',
        '/contact',
        '/services',
        '/patents',
        '/trademarks',
        '/copyright',
        '/prior-work',
        '/resources',
        '/testimonials',
        '/helpful-links',
        '/flat-fees',
        '/success',
        '/privacy-policy',
        '/terms-of-service'
      ]
    }
  },

  // 🔧 Fix route rules to ensure proper indexing
  routeRules: {
    '/': { 
      prerender: true, 
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/about': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/contact': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/patents': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/trademarks': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/copyright': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/services': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/testimonials': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/flat-fees': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/resources': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/helpful-links': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/prior-work': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/privacy-policy': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/terms-of-service': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/success': { 
      prerender: true,
      headers: { 'X-Robots-Tag': 'index, follow' },
      robots: 'index, follow'
    },
    '/drafts/**': { headers: { 'X-Robots-Tag': 'noindex, nofollow' } },
  },

  compatibilityDate: '2025-04-08',

  runtimeConfig: {
    public: {
      gtag: process.env.NUXT_PUBLIC_GTAG,
      ahrefsKey: process.env.NUXT_PUBLIC_AHREFS_KEY
    }
  }
})
